### ISSUE TITLE
Testimonials from other users

### ISSUE THREAD

**Issue by BenWilliams89** [BenWilliams89/mental-health-website#10]
As a user, I want testimonials from other users so that I can feel reassured by their experiences.

**Acceptance Criteria:**

- [ ] Include a section for user testimonials.

- [ ] Testimonials are styled using Bootstrap components.

**Tasks:**

- [x] Collect and write user testimonials.

- [ ] Design and implement testimonial section using Bootstrap.
