### ISSUE TITLE
easy-to-navigate layout

### ISSUE THREAD

**Issue by BenWilliams89** [BenWilliams89/mental-health-website#7]
As a user, I want an easy-to-navigate layout so that I can quickly find the information I need.

**Acceptance Criteria:**

- [x] Clear navigation menu at the top of the page.

- [x] Sections are logically organized and easy to find.

**Tasks:**

- [x] Design navigation menu.

- [x] Implement and test menu with Bootstrap.
