### ISSUE TITLE
adding additional pages

### ISSUE THREAD

**Issue by BenWilliams89** [BenWilliams89/mental-health-website#8]
As a user I want to see more information on who you are as a business/charity.

**Acceptance Criteria**

- [ ] Add a about us page

**Tasks**

- [ ] Add about us page to the website and build in HTML and bootstrap
- [x] Link to other helpful resources from the page
