### ISSUE TITLE
visual aids such as images

### ISSUE THREAD

**Issue by BenWilliams89** [BenWilliams89/mental-health-website#9]
As a user, I want visual aids such as images or icons to enhance the understanding of content.

**Acceptance Criteria:**

- [x] Include relevant images or icons in each section.

- [x] Ensure images/icons are consistent with the theme.

**Tasks:**

- [x] Select and include appropriate images/icons.

- [x] Implement visual aids within the content using Bootstrap.
